name: CI

on:
  push:
    paths-ignore: ['**.md', '**.org']
  pull_request:
    paths-ignore: ['**.md', '**.org']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['27.2', '28.2', 'snapshot']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: cache-cask-packages
      uses: actions/cache@v2
      id: cache-cask-packages
      with:
        path: .cask
        key: cache-cask-packages-000

    - name: cache-cask-executable
      uses: actions/cache@v2
      id: cache-cask-executable
      with:
        path: ~/.cask
        key: cache-cask-executable-000

    - name: setup-cask
      uses: cask/setup-cask@master
      if: steps.cache-cask-executable.outputs.cache-hit != 'true'
      with:
        version: snapshot

    - name: Setup $GITHUB_PATH
      run: echo "$HOME/.cask/bin" >> $GITHUB_PATH

    - name: Install Leiningen
      run: sudo apt-get update && sudo apt-get install make leiningen -y

    - name: Test the project
      run: |
        make elpa
        emacs --version
        make test
